hiddenimports = [
    "base64",
    "math",
    "json",
    "os",
    "re",
    "shutil",
    "string",
    "sys",
    "time",
    "dataclasses",
    "pathlib",
    "typing",
    "ctypes",
    "ctypes.wintypes",
    "winreg",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "cryptography.fernet",
    # QR code support and backend
    "qrcode",
    "qrcode.image",
    "qrcode.image.pil",
    "PIL",
    "PIL.Image",
    "PIL.PngImagePlugin",
]
